### ISSUE TITLE
git clone failed

### ISSUE THREAD

**Issue by fxgenstudio** [jazzbre/imguibgfx-beef#1]
git.exe clone --progress --recursive -v "https://github.com/jazzbre/imguibgfx-beef.git" "C:\Projects\Beef\imguibgfx-beef"
Cloning into 'C:\Projects\Beef\imguibgfx-beef'...
POST git-upload-pack (152 bytes)
POST git-upload-pack (190 bytes)
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 71 (delta 27), reused 64 (delta 20), pack-reused 0
Receiving objects: 100% (71/71), 287.17 KiB | 250.00 KiB/s, done.
Resolving deltas: 100% (27/27), done.
Submodule 'submodules/bx' (https://github.com:bkaradzic/bx.git) registered for path 'submodules/bx'
Submodule 'submodules/cimgui' (https://github.com:cimgui/cimgui.git) registered for path 'submodules/cimgui'
Submodule 'submodules/imgui-beef' (https://github.com/jazzbre/imgui-beef.git) registered for path 'submodules/imgui-beef'
Cloning into 'C:/Projects/Beef/imguibgfx-beef/submodules/bx'...
fatal: unable to access 'https://github.com:bkaradzic/bx.git/': URL using bad/illegal format or missing URL
fatal: clone of 'https://github.com:bkaradzic/bx.git' into submodule path 'C:/Projects/Beef/imguibgfx-beef/submodules/bx' failed
Failed to clone 'submodules/bx'. Retry scheduled
Cloning into 'C:/Projects/Beef/imguibgfx-beef/submodules/cimgui'...
fatal: unable to access 'https://github.com:cimgui/cimgui.git/': URL using bad/illegal format or missing URL
fatal: clone of 'https://github.com:cimgui/cimgui.git' into submodule path 'C:/Projects/Beef/imguibgfx-beef/submodules/cimgui' failed
Failed to clone 'submodules/cimgui'. Retry scheduled
Cloning into 'C:/Projects/Beef/imguibgfx-beef/submodules/imgui-beef'...
remote: Enumerating objects: 135, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 135 (delta 48), reused 104 (delta 28), pack-reused 0
Receiving objects: 100% (135/135), 3.02 MiB | 934.00 KiB/s, done.
Resolving deltas: 100% (48/48), done.
Cloning into 'C:/Projects/Beef/imguibgfx-beef/submodules/bx'...
fatal: unable to access 'https://github.com:bkaradzic/bx.git/': URL using bad/illegal format or missing URL
fatal: clone of 'https://github.com:bkaradzic/bx.git' into submodule path 'C:/Projects/Beef/imguibgfx-beef/submodules/bx' failed
Failed to clone 'submodules/bx' a second time, aborting

git did not exit cleanly (exit code 1) (8969 ms @ 03/12/2020 21:41:38)

**Comment by jazzbre** [comment]
Fixed, you'll probably need to delete the repo and clone again though.
Thanks!
